[package]
name    = "portfolio_rayon_nightly"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level       = 3
lto             = true
codegen-units   = 1
